// Builds the frontend into dist/frontend: static assets + runtime config.js
// generated from deployment outputs. Nothing is hardcoded in source.
//
// Usage: node scripts/build.js [--api-url URL] [--ws-url URL] [--region R]
//                             [--user-pool-id ID] [--client-id ID]
// Defaults fall back to local dev values.

import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'frontend');
const dest = path.join(root, 'dist', 'frontend');

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i !== -1 ? process.argv[i + 1] : fallback;
}

const config = {
  apiBaseUrl: arg('--api-url', 'http://localhost:8787'),
  wsBaseUrl: arg('--ws-url', 'ws://localhost:8787'),
  region: arg('--region', 'us-east-1'),
  cognito: {
    userPoolId: arg('--user-pool-id', 'dev-local'),
    clientId: arg('--client-id', 'dev-local'),
  },
};

if (existsSync(dest)) rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });

cpSync(src, dest, {
  recursive: true,
  filter: (s) => !s.endsWith('config.js'),
});

writeFileSync(
  path.join(dest, 'config.js'),
  `// Generated by scripts/build.js from CloudFormation outputs — DO NOT EDIT.\n` +
    `// Deployed configuration lives here, never in source files.\n` +
    `window.LINELESS_CONFIG = ${JSON.stringify(config, null, 2)};\n`,
);

console.log(`Frontend built: ${dest}`);
console.log(`  API: ${config.apiBaseUrl}`);
console.log(`  WS:  ${config.wsBaseUrl}`);
console.log(`  Cognito pool: ${config.cognito.userPoolId}`);
